[package]
name = "eight-driver"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "src/bin/eightc.rs"
name = "eightc"

[dependencies]
clap = { workspace = true }
miette = { workspace = true, features = ["fancy"] }
pathdiff = "0.2.3"
ron = { workspace = true }
thiserror = { workspace = true }
nom = "7.1.3"

eight-middle = { path = "../eight-middle" }
eight-syntax = { path = "../eight-syntax" }
eight-diagnostics = { path = "../eight-diagnostics" }
eight-codegen-llvm = { path = "../eight-codegen-llvm" }

[dev-dependencies]
eight-macros = { path = "../eight-macros", features = ["assertion-macros"] }
