[workspace]
resolver = "2"
members = [
    "compiler/eight-codegen-llvm",
    "compiler/eight-driver",
    "compiler/eight-macros",
    "compiler/eight-middle",
    "compiler/eight-rt",
    "compiler/eight-support",
    "compiler/eight-syntax",
    "tools/eight-regtest",
    "tools/eight-xtask",
]

[profile.dev.package]
similar.opt-level = 3

[workspace.dependencies]
clap = { version = "4.3.19", features = ["derive"] }
bumpalo = { version = "3.11.1", features = ["collections"] }
miette = { version = "7.4.0", features = ["derive"] }
pretty = "0.12.3"
serde = { version = "1.0.216", features = ["derive"] }
ron = { version = "0.8.1" }
thiserror = "2.0.6"
