[package]
name = "eight-mir"
version = "0.1.0"
edition = "2021"

[dependencies]
eight-diagnostics = { path = "../eight-diagnostics" }
eight-hir = { path = "../eight-hir" }
eight-macros = { path = "../eight-macros" }
eight-middle = { path = "../eight-middle" }

bumpalo = { workspace = true }
miette = { workspace = true }
pretty = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
eight-macros = { path = "../eight-macros", features = ["assertion-macros"] }
