[package]
name = "eight-middle"
version = "0.1.0"
edition = "2021"

[dependencies]
eight-macros = { path = "../eight-macros" }
eight-support = { path = "../eight-support" }
eight-syntax = { path = "../eight-syntax" }

bumpalo = { workspace = true }
pretty = { workspace = true }

[dev-dependencies]
eight-macros = { path = "../eight-macros", features = ["assertion-macros"] }
