//===----- DiagnosticEmitter ---===//
//
// Part of the XD Compiler Project, under the Apache License v2.0 with
// LLVM Exceptions. See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#include "xd/TableGen/DiagnosticEmitter.h"
#include "llvm/TableGen/Record.h"
#include "llvm/TableGen/TableGenBackend.h"

using namespace llvm;
using namespace xd;

auto DiagnosticEmitter::emit(raw_ostream &OS) -> bool {
  emitSourceFileHeader("File generated by xd-tablegen", OS);
  auto Diagnostics = RK.getAllDerivedDefinitions("Diagnostic");
  for (auto *Diag : Diagnostics)
    emitDiagnostic(Diag, OS);
  return false;
}

auto DiagnosticEmitter::emitDiagnostic(const Record *Rec,
                                       raw_ostream &OS) -> void {
  OS << Rec->getName() << "\n";
}

auto DiagnosticEmitter::emitDiagnosticIdentifiers(ArrayRef<const Record *> Recs)
    -> void {}
