//===----- DiagnosticEmitter ---===//
//
// Part of the XD Compiler Project, under the Apache License v2.0 with
// LLVM Exceptions. See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#include "xd/TableGen/DiagnosticEmitter.h"
#include "llvm/TableGen/Record.h"
#include "llvm/TableGen/TableGenBackend.h"
#include <cassert>

using namespace llvm;
using namespace xd;

auto DiagnosticEmitter::emit(raw_ostream &OS) -> bool {
  emitSourceFileHeader("File generated by xd-tablegen", OS);
  auto Diagnostics = RK.getAllDerivedDefinitions("Diagnostic");
  // Process diagnostics by emitting their kinds
  assert(Diagnostics.size() > 0 &&
         "Cannot emit diagnostics with zero configured records. This is "
         "required for generating the enum kind");
  OS << "#ifndef XD_BASIC_DIAGNOSTICS_TD" << "\n";
  OS << "#define XD_BASIC_DIAGNOSTICS_TD" << "\n\n";
  OS << "#include <cstdint>" << "\n\n";
  OS << "namespace xd {" << "\n";
  OS << "enum class DiagnosticKind: uint8_t {" << "\n";
  for (auto *Diag : Diagnostics)
    OS << "  " << Diag->getName() << "," << "\n";
  OS << "};\n";

  // Emit sentinel values for first and last record in order to allow RTTI to
  // use constant kinds.
  auto *FirstRK = Diagnostics[0];
  auto *EndRK = Diagnostics[Diagnostics.size() - 1];
  OS << "static auto FirstDiagnosticKind = DiagnosticKind::"
     << FirstRK->getName() << ";" << "\n";
  OS << "static auto LastDiagnosticKind = DiagnosticKind::" << EndRK->getName()
     << ";" << "\n";

  OS << "\n"
     << "#include \"xd/Basic/Diagnostic.h.inc\"" << "\n";

  for (auto *Diag : Diagnostics) {
    OS << "\n";
    OS << "class " << Diag->getName() << "Diagnostic : public Diagnostic {"
       << "\n";
    OS << "};" << "\n";
  }

  // Close the namespace and include guard
  OS << "} // namespace xd" << "\n\n";
  OS << "#endif // XD_BASIC_DIAGNOSTICS_TD" << "\n";
  return false;
}
