[package]
name = "eight-syntax"
version = "0.1.0"
edition = "2021"

[features]
default = ["serde"]
serde = ["dep:serde"]

[dependencies]
eight-macros = { path = "../eight-macros" }
eight-support = { path = "../eight-support" }

bumpalo = { workspace = true }
serde = { workspace = true, optional = true }

[dev-dependencies]
eight-macros = { path = "../eight-macros", features = ["assertion-macros"] }
