[package]
name = "eight-codegen-llvm"
version = "0.1.0"
edition = "2021"

[dependencies]
eight-macros = { path = "../eight-macros" }
eight-diagnostics = { path = "../eight-diagnostics" }
eight-middle = { path = "../eight-middle" }

inkwell = { version = "0.5.0", features = ["llvm15-0"] }
thiserror = { workspace = true }
miette = { workspace = true }
