[package]
name = "eight-diagnostics"
version = "0.1.0"
edition = "2021"

[features]
default = ["serde"]
serde = ["dep:serde"]

[dependencies]
eight-macros = { path = "../eight-macros" }
miette = { workspace = true }
serde = { workspace = true, optional = true }
thiserror = { workspace = true }
