[package]
name = "hachi-parse"
version = "0.1.0"
edition = "2021"

[features]
default = ["serde"]
serde = ["dep:serde"]

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3

[dependencies]
insta = { version = "1.41.1", features = ["serde", "ron", "glob"] }
miette = { version = "7.4.0", features = ["derive"] }
serde = { version = "1.0.216", features = ["derive"], optional = true }
thiserror = "2.0.6"
